# Stage 1: Build Nativo com GraalVM
FROM ghcr.io/graalvm/native-image-community:17 AS build
WORKDIR /app

USER root
# Instalar o maven no container
RUN microdnf install maven -y

# Copiar apenas o pom.xml primeiro (mantendo o cache do Docker)
COPY pom.xml .

# Copiar o código fonte
COPY src ./src

# 1. DECLARAR OS ARGs NO STAGE DE BUILD
# Isso permite que o Dokploy injete os valores neste estágio
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG FLYWAY_ENABLED
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG OPENAI_API_KEY

# 2. PASSAR OS ARGs PARA O MAVEN
# O Spring AOT vai usar esses valores para preencher as variáveis do application.properties durante a compilação
RUN mvn native:compile -Pnative -DskipTests \
    -DDB_URL="${DB_URL}" \
    -DDB_USERNAME="${DB_USERNAME}" \
    -DDB_PASSWORD="${DB_PASSWORD}" \
    -DFLYWAY_ENABLED="${FLYWAY_ENABLED}" \
    -DGOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}" \
    -DGOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}" \
    -DOPENAI_API_KEY="${OPENAI_API_KEY}"


# Stage 2: Runtime Stage (Imagem extremamente leve)
FROM debian:bookworm-slim
WORKDIR /app

# Criar usuário não-root para segurança
RUN addgroup --system spring && adduser --system spring --ingroup spring
USER spring:spring

# Copiar o binário gerado no estágio anterior
# Atenção: verifique se o nome gerado é 'quiz-aleitamento' ou 'quiz-aleitamento-app'
COPY --from=build /app/target/quiz-aleitamento /app/app

# 3. REDECLARAR OS ARGs NO STAGE DE RUNTIME
# Como mudamos de Stage, os ARGs anteriores "sumiram". Precisamos deles de novo para as ENVs.
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG FLYWAY_ENABLED
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG OPENAI_API_KEY

# Variáveis de ambiente
ENV DB_URL=${DB_URL} \
    FLYWAY_ENABLED=${FLYWAY_ENABLED} \
    DB_USERNAME=${DB_USERNAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    OPENAI_API_KEY=${OPENAI_API_KEY}

EXPOSE 8080

# No modo nativo, executamos o binário diretamente
ENTRYPOINT ["./app"]
